name: ali-app
services:
- name: web
  github:
    repo: WarDaddy146/Portfolio
    branch: master
    deploy_on_push: true
  build_command: pnpm install && pnpm run build
  run_command: pnpm start
  environment_slug: node-js
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
